### ISSUE TITLE
jasmine does not have method getFixtures

### ISSUE THREAD

**Issue by adam-lynch** [velesin/jasmine-jquery#99]
I'm using JsTestDriver.

Console output:

> ```
> setting runnermode QUIET
> Chrome: Reset
> Chrome: Reset
> F
> Total 1 tests (Passed: 0; Fails: 1; Errors: 0) (187.00 ms)
>   Chrome 23.0.1271.95 Windows: Run 1 tests (Passed: 0; Fails: 1; Errors 0) (187.00 ms)
>     blockquote highlighter.doesn't change the scroll depth to the top of the first blockquote when jumpToFirstQuote is not true failed (187.00 ms): RangeError: RangeError: Maximum call stack size exceeded
> TypeError: TypeError: Object #<Object> has no method 'getFixtures'
> 
> 
>            TypeError: Object #<Object> has no method 'getFixtures'
> ```

All I'm doing is setting the fixture path in `beforeEach` and I've one empty test.

``` javascript
jasmine.getFixtures().fixturesPath = 'fixtures';
```

My JsTestDriver config:

``` yaml
server: http://localhost:9876

load:
- Jasmine/lib/jasmine-1.2.0/jasmine.js
- JasmineAdapter/src/*
- jquery/1.8.3/jquery.min.js
- jasmine-jquery/jasmine-jquery.js
- ../bootstrap/*.js #sets up the testing environment
- ../util/*.js #reusable JS functions
- ../../source/js/*.js #source code to test
- ../*.js #test specs

serve:
 - ../fixtures/html/*.html
 - ../fixtures/styling/*.css

timeout: 90
```

(To be honest, I'm not sure if I need `serve`, added it after seeing @justlaputa's config in [#95](https://github.com/velesin/jasmine-jquery/issues/95#issuecomment-9293180))

What's strange is that when I `console.debug(jasmine)` in the `beforeEach`, it **does** contain `getFixtures`;

![**does** contain `getFixtures`](https://f.cloud.github.com/assets/1427241/2164/07dcaba4-41a6-11e2-9789-68af249b5de0.PNG).
### Replicate

[See/get the code](https://github.com/adam-lynch/purify-jasmine-jquery-fixtures-issue/), I set up a [repo](https://github.com/adam-lynch/purify-jasmine-jquery-fixtures-issue/) for this issue.
To run the tests:
1.  Update the browser path in [test/run-tests.sh](https://github.com/adam-lynch/purify-jasmine-jquery-fixtures-issue/blob/master/test/run-tests.sh) (at the end) to your own path to Chrome. If you're on Linux, it's probably `/usr/bin/google-chrome`.
2. Run `sh run-tests.sh` in the command-line (cygwin is fine).
